Init homepage UI
Leading-AI-Development-Solutions/MAIA pull request #3
Opened 2024-02-04 03:19 UTC by Graham-Berry

This PR Creates a homepage, an about page, and page routing logic.

2024-02-04 03:22 UTC, Hodgdonc approved these changes

2024-02-05 08:51 UTC, sophiekummer reviewed
There seem to be some issues with the functionality on MacOS that will need to be addressed before this can be merged with master.

2024-02-23 02:47 UTC, Hodgdonc approved these changes

2024-02-23 02:49 UTC, Hodgdonc requested changes
Needs linting/code formatting

2024-02-23 03:01 UTC, Hodgdonc approved these changes
LGTM

2024-02-23 21:44 UTC, hwk01 commented on aboutPage.py
> +        descText = "MAIA is a platform designed for AI competitions that provides a modular 2D\nsimulation environment for which students write AI to control competing agents.\nThe goal is to give co
I'm not sure how this appears on windows, but on mac some of the lines are cut out early or wraparound. 
<img width="755" alt="Screen Shot 2024-02-23 at 4 44 19 PM" src="https://github.com/Leading-AI-Development-Solutions/MAIA/assets/94702589/d7890a3c-80b0-4169-8d67-021303011163">

2024-02-23 21:49 UTC, hwk01 approved these changes
Everything runs perfectly well on my machine, one thing to note is when you go into the setup page if you don't put it into full screen you do not see that you need to select a team and a map.

2024-02-28 02:22 UTC, merged