Update setup page
Leading-AI-Development-Solutions/MAIA pull request #4
Opened 2024-02-11 17:09 UTC by HenryKindler

Many Changes to the Basic set-up page, including reorganization of elements, fusion of the "Build Sim" button and the "Run Sim with UI" button into the "Start Game" button, addition of the "Advanced Config" button, elimination of the "Select Map" button with that functionality now occurring when a map option is clicked on, the addition of a page title, and changes were made in the ui_widgets.py folder to increasing  font sizes.

2024-02-11 17:11 UTC, Graham-Berry approved these changes

2024-02-11 18:33 UTC, sophiekummer requested changes
There needs to be some clean up of this code before it's merged. Mostly commented out code that can be deleted.

2024-02-11 18:33 UTC, sophiekummer commented on ui_setup.py
> +        print("Hello world") #okay so this works, but self.selectMap wont sork cuase on self
Does it have a purpose or can it be removed before being merged into main?

2024-02-11 18:33 UTC, sophiekummer commented on ui_setup.py
> +        self.configure(bg=DARKCOLOR) #bg is background i think
bg is background

2024-02-11 18:33 UTC, sophiekummer commented on ui_setup.py
> +        self.BuildUI()
This white space will be picked up by linter, if we could remove it now, that would be ideal.

2024-02-11 18:33 UTC, sophiekummer commented on ui_setup.py
> +        #below four lines were replaced by below fifth and sixth line
The lines that this is referencing could be deleted. If your concerned that there won't be a record of them if they need to be changed back for some reason, GitHub keeps track of previous versions, so they wont be lost.

2024-02-11 18:33 UTC, sophiekummer commented on ui_setup.py
> +        # self.btnRunSimWithoutUI = tk.Button(self.fmSimUI,text="Run Sim Without UI",command=self.runSimWithoutUI)
This could also be deleted.

2024-02-11 18:33 UTC, sophiekummer commented on ui_setup.py
> +        self.btnAdvancedConfig = uiButton(master=self.advancedConfigBtnFrame,command=self.runAdvancedSettings,text="Advanced Config") #have to change command later to navigate to advanced config
I'm pretty sure the command got changed so that it does go to advanced config, so this comment should be deleted.

2024-02-11 18:33 UTC, sophiekummer commented on ui_setup.py
> +        self.mapFrame.pack(side=tk.LEFT, fill=tk.BOTH,padx=10, pady=10) #HK set side to left
Comment is unnecessary.

2024-02-11 18:33 UTC, sophiekummer commented on ui_setup.py
> +        #self.btnSelectMap = uiButton(master=self.mapSelectFrame,command=self.selectMap,text="Select Map") #button
If this button is no longer in use (I feel like this is the button that used to allow you to select a map and therefore isn't used) then this commended out section can be deleted.

2024-02-11 18:33 UTC, sophiekummer commented on ui_setup.py
> +        #self.playPoolFrameLeft = uiQuietFrame(master=self.playPoolFrame)
These comments can be deleted.

2024-02-11 18:33 UTC, sophiekummer commented on ui_setup.py
> +
This amount of white space is excessive.

2024-02-11 18:33 UTC, sophiekummer commented on ui_setup.py
> +    #def runSimWithUI(self):
Delete this commented out section.

2024-02-11 18:33 UTC, sophiekummer commented on ui_widgets.py
> +            font=(12) #changed by HK, originally no font parameter
This comment is unneccesary.

2024-02-17 13:23 UTC, sophiekummer approved these changes

2024-02-17 13:23 UTC, merged